### ISSUE TITLE
Add shooting script

### ISSUE THREAD

**Issue by yejun614** [yejun614/unity_fps_game#5]
# Todo
- [x] Add Sample Gun
- [x] Fire a bullet when player click on the mouse left button
- [x] Over time, bullets disappear
