### ISSUE TITLE
Add Player Sounds

### ISSUE THREAD

**Issue by yejun614** [yejun614/unity_fps_game#9]
# Todo
- [ ] Add sound assets (from asset store)
- [ ] Add shooting sound
- [ ] Add movement sound
